# Configuration for GitHub Pages
include:
  - _config.yml
  - .gitignore
  - README.md
  - LICENSE

# Exclude these files from the built site
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - .github/

# Site settings
title: Chess Assist
description: A modern chess assistant web application
url: "https://your-username.github.io"
baseurl: "/chess-assist"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO settings
lang: en_US
author: Roger Aparecido Silva
